- cmd/rbac/main.go
- cmd/rbac_crud/main.go
> Project layout was fixed

- api/rbac/rbac-api.yaml
> Add OpenAPI spec for RBAC CRUD service

- api/ims/ims-api.yaml
добавили скелет логина и рефреша токена
> Example of auntintification for Post to ims-api.yaml was added

- api/timetable/timetable.yml
> timetabling service OpenApi specification

- api/ugm/ugm.yaml
> issue 19, added OpenAPI spec. for User and Group Management

- api/ims/ims-api.yaml
> Sign Up Flow API

- pkg/signup/repository/postgresql/migrations/SignUp_init.down.sql
- pkg/signup/repository/postgresql/migrations/SignUp_init.up.sql
> SQL-scripts for SignUp

- pkg/config/config.go
> add config package

- pkg/rbac/api/handlers/crud_handlers.go
- pkg/rbac/api/routers/router.go
- pkg/rbac/service/service.go
> issue-50, removed business logic from handlers to service package

- api/ims/ims-api.yaml
> Change password use case opeaAPI spec

- .gitignore
- cmd/rbacgen/main.go
- pkg/rbac/repository/postgres/postgres.go
- pkg/rbac/service/service.go
> issue-68, implemented functions from repository/postgres as RolesRepository's methods

- ui/src/app/app.component.html
- ui/src/app/app.component.sass
- ui/src/app/app.component.ts
- ui/src/app/app.module.ts
- ui/src/app/calendar/calendar.component.ts
- ui/src/app/header/header.component.html
- ui/src/app/header/header.component.sass
- ui/src/app/header/header.component.ts
- ui/src/app/in-memory-data.service.ts
- ui/src/app/models/Lesson.ts
- ui/src/app/search-result/search-result.component.html
- ui/src/app/search-result/search-result.component.sass
- ui/src/app/search-result/search-result.component.spec.ts
- ui/src/app/search-result/search-result.component.ts
- ui/src/app/shared/timetable-http.service.ts
- ui/src/app/sidebar/sidebar.component.html
- ui/src/app/sidebar/sidebar.component.sass
- ui/src/app/sidebar/sidebar.component.ts
- ui/src/app/slider-menu/delete-dialog.html
- ui/src/app/slider-menu/slider-menu.component.html
- ui/src/app/slider-menu/slider-menu.component.sass
- ui/src/app/slider-menu/slider-menu.component.ts
- ui/src/app/slider-menu/success-dialog.html
- ui/src/app/timetable.service.ts
- ui/src/app/timetable/timetable.component.html
- ui/src/app/timetable/timetable.component.sass
- ui/src/app/timetable/timetable.component.ts
- ui/src/styles.sass
> Creation of search-result component

- pkg/pwd/hash.go
- pkg/pwd/random.go
`hash.go` generates password hash from password and salt
`random.go` generates random string for salt or token with specified size
Closes #92
> Issue-92, Hash and Salt functions created

- cmd/codegen/main.go
> Create codegen example

- cmd/rbacgen/main.go
- go.sum
- pkg/rbac/api/handlers/crud_handlers.go
- pkg/rbac/repository/postgres/postgres.go
- pkg/rbac/repository/postgres/role.go
- pkg/rbac/service/service.go
closes #69 
closes #78
closes #14
> issue-69, implemented transactions in repository methods where needed

- pkg/rbac/api/middleware/middleware.go
- pkg/rbac/opa/opa.go
> issue-89, implemented passing context.Context from middleware to opa

- pkg/jwt/jwt.go
- pkg/jwt/models.go
> issue-71, implemented user JWT generation

- pkg/rbac/api/middleware/authorizationCache.json
- pkg/rbac/opa/authorization.rego
- pkg/rbac/opa/models.go
- pkg/rbac/opa/opa.go
> issue-87, fixed path recognition in authorization.rego

- cmd/rbac/config.go
- cmd/rbac/main.go
- cmd/rbac/rbac-service-example-config.yaml
- cmd/rbacgen/config.go
- cmd/rbacgen/main.go
- cmd/rbacgen/rbacgen-service-example-config.yaml
- pkg/db/config.go
- pkg/rbac/repository/postgres/postgres.go
> issue-120, implemented passing db object to repository constructor

- cmd/rbac/main.go
- cmd/rbacgen/main.go
> issue-121, attached suitable and more meaningful messages to errors

- pkg/rbac/api/middleware/middleware.go
- pkg/rbac/opa/errors.go
- pkg/rbac/opa/opa.go
> issue-129, refactored GetDecision func in opa package to return error instead of bool

- pkg/rbac/opa/models.go
> issue-130, removed redundant types from opa package

- cmd/rbac/main.go
- pkg/pubsub/client.go
- pkg/pubsub/envelope.go
- pkg/pubsub/subscriber.go
- pkg/rbac/service/service.go
> issue-94, implement group subscription

- cmd/codegen/main.go
- pkg/models/ims.go
- pkg/models/rbac.go
> issue-113,  to the folder where the code is generated

- cmd/ims/config.go
- cmd/ims/ims-service-example-config.yaml
- cmd/ims/main.go
- pkg/ims/api/routers/router.go
`main.go`: updated
`router.go`: modified
Closes: #159
> main.go for SignUp

- api/ims/ims-api.yaml
- pkg/ims/api/handlers/handlers.go
- pkg/ims/api/routers/router.go
- pkg/ims/models/models.go
- pkg/ims/repository/postgresql/credentials_repository.go
- pkg/ims/service/service.go
- pkg/ims/validate/data.go
> Implementation ChangePassword service and handlers

- pkg/pubsub/envelope.go
- pkg/pubsub/subscriber.go
- pkg/rbac/cache.go
> issue-170, add interface for Envelope

- pkg/rbac/cache.go
- pkg/rbac/cache_test.go
- pkg/rbac/types.go
> issue-149, added unit tests for Cache Update method and fixed it

- cmd/rbacgen/roleTmpl.yaml
- pkg/rbac/repository/postgres/postgres.go
> issue 176, fixed repository.CreateRoleTmpl

- cmd/rbac/config.go
- cmd/rbac/main.go
- cmd/rbac/rbac-service-example-config.yaml
- cmd/rbacgen/config.go
- cmd/rbacgen/main.go
- cmd/rbacgen/rbacgen-service-example-config.yaml
- go.mod
- pkg/mq/config.go
- pkg/pubsub/client.go
- pkg/pubsub/config.go
> issue-184, implemented configuration of MQ connection

- Dockerfile.ims
- Dockerfile.ims-db-migrator
- cmd/ims/ims-service-example-config.yaml
- cmd/ims/main.go
- docker-compose.yml
- pkg/ims/repository/postgresql/migrations/000007_change_table_for_access_token.down.sql
- pkg/ims/repository/postgresql/migrations/000007_change_table_for_access_token.up.sql
- pkg/ims/repository/postgresql/migrations/000008_change_access_token.up.sql
> issue-188, containerized ims service with it's dependencies
